[template.environment]
  GQL_HOST = "WordPress URL https://wordpress-1346312-4943553.cloudwaysapps.com/graphql"
  NUXT_IMAGE_DOMAINS = "https://wordpress-1346312-4943553.cloudwaysapps.com/graphql"

[build]
  command = "nuxt generate"

[images]
  remote_images = ["https://wordpress-1346312-4943553.cloudwaysapps.com/.*"]
